### ISSUE TITLE
Implement Adafruit IMU for positioning

### ISSUE THREAD

**Issue by nc4pk** [tsdch-robotics/ftc5459#18]
This is a tracking bug for the integration of the Adafruit IMU into our autonomous opmodes. A buggy initial version was committed in 5d38b83. 

### TODO
- [ ] refactor logging code to use telemetry instead of Android's built-in logging
- [ ] delete dead gyro code
- [ ] implement turn function with IMU data
