### ISSUE TITLE
Tracking bug for Base5459

### ISSUE THREAD

**Issue by nc4pk** [tsdch-robotics/ftc5459#6]
This is a tracking bug for implementing a "super-base class" for both autonomous and teleop modes. It was first implemented in 6058a7e.

The new base class extends `OpMode` instead of `LinearOpMode` to make teleop work correctly.

Things to do immediately:
 - [x] refactor initialization code out of teleop
 - [x] change all autonomous programs to override `start()` instead of `runOpMode()`
  - *rationale*: `runOpMode()` only exists in LinearOpMode
 - [x] override the `stop()` method and halt all drive motors

Things to test:
 - [x] our custom `initialization()` method changed to an override of `OpMode`'s `init()` method; does this change anything?
 - [x] where should `waitForStart()` go? should it move outside the `init()` method?

**Comment by nc4pk** [comment]
autonomous programs override `loop()` instead of `start()`

**Comment by nc4pk** [comment]
`waitForStart() doesn't exist in `OpMode` so this method call was removed

**Comment by tsdch-robotics** [comment]
- [ ] we need to override the `stop()` method and stop all drive motors
